vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.0.0/24"
env = "dev"
instance_type = "t2.micro"
avail_zone = "us-east-2a"
public_key = "/Users/gopi/.ssh/id_rsa.pub"
private_key = "/Users/gopi/.ssh/id_rsa"